openapi: 3.0.0
info:
  version: "1.0"
  title: 🌊 Ketner Lake
  description: API server for Ketner Lake products
  contact:
    email: parkerkrhoyt@gmail.com
  license:
    name: MIT
externalDocs:
  description: Find out more about Ketner Lake
  url: https://ketnerlake.com
servers:
  - url: http://localhost:3000/v1
  - url: https://xmt62bgtjg.us-west-2.awsapprunner.com/v1
tags:
  - name: 📒 Account
    description: Account on the API system
  - name: 🗓️ Calendar
    description: Calendar on the API system
  - name: 🎟️ Event
    description: Event on the API system
paths:
  /account/login:
    post:
      tags:
        - 📒 Account
      summary: Login to system account
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: The session ID for the account
          content:
            application/json:
              schema:
                type: string
                format: uuid
  /account/register:
    post:
      tags:
        - 📒 Account
      summary: Register new account with system
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: The session ID for the account
          content:
            application/json:
              schema:
                type: string
                format: uuid   
  /account/test:
    get:
      tags:
        - 📒 Account
      summary: Testing if the service is operational
      operationId: testAccount
      responses:
        '200':
          description: Endpoint and version information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string              
                    format: date    
  /calendar:
    get:
      tags:
        - 🗓️ Calendar
      summary: Read all calendars for a specific account
      operationId: readAllCalendars
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account      
      responses:
        '200':
          description: An array of calendar objects
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Calendar' 
  /calendar/{calendarId}:
    get:
      tags:
        - 🗓️ Calendar
      summary: Read a specific calendar for a specific account
      operationId: readCalendar
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account    
        - in: path
          name: calendarId
          schema:
            type: string
            format: uuid
            description: Identifier for specific calendar    
          required: true              
      responses:
        '200':
          description: A single calendar object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'  
    post:
      tags:
        - 🗓️ Calendar
      summary: Create a calendar for a specific account
      operationId: createCalendar
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account   
        - in: path
          name: calendarId
          schema:
            type: string
            format: uuid
            description: Identifier for specific calendar    
          required: true                           
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Calendar'
      responses:
        '200':
          description: The calendar object created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'                                                                  
    put:
      tags:
      - 🗓️ Calendar
      summary: Update a specific calendar for a specific account
      operationId: updateCalendar
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account   
        - in: path
          name: calendarId
          schema:
            type: string
            format: uuid
            description: Identifier for specific calendar    
          required: true                               
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Calendar'                                                                  
      responses:
        200:
          description: The calendar object updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'                
    delete:
      tags:
        - 🗓️ Calendar
      summary: Delete a specific calendar for a specific account
      operationId: deleteCalendar
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account   
        - in: path
          name: calendarId
          schema:
            type: string
            format: uuid
            description: Identifier for specific calendar    
          required: true                           
      responses:
        '200':
          description: The created calendar object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
  /calendar/test:
    get:
      tags:
        - 🗓️ Calendar
      summary: Testing if the service is operational
      operationId: testCalendar
      responses:
        '200':
          description: Endpoint and version information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string              
                    format: date                                             
  /event:
    get:
      tags:
        - 🎟️ Event
      summary: Read all calendar events for a specific account
      operationId: readAllEvents
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account      
      responses:
        '200':
          description: An event object
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Event'
  /event/year/{year}:
    get:
      tags:
        - 🎟️ Event
      summary: Read all calendar events for a specific year for a specific account
      operationId: readAllEventsForYear
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account      
        - in: path
          name: year
          schema:
            type: integer
            description: Full (four-digit) year    
          required: true                          
      responses:
        '200':
          description: An event object
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Event'                  
  /event/{eventId}:
    get:
      tags:
        - 🎟️ Event
      summary: Read specific calendar event for a specific account
      operationId: readEvent
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account    
        - in: path
          name: eventId
          schema:
            type: string
            format: uuid
            description: Identifier for specific event    
          required: true              
      responses:
        '200':
          description: An event object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'  
    post:
      tags:
        - 🎟️ Event
      summary: Create calendar event for a specific account
      operationId: createEvent
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account   
        - in: path
          name: eventId
          schema:
            type: string
            format: uuid
            description: Identifier for specific event    
          required: true                           
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Echo of the created event object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'                                                                  
    put:
      tags:
      - 🎟️ Event
      summary: Update specific calendar event for a specific account
      operationId: updateEvent
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account   
        - in: path
          name: eventId
          schema:
            type: string
            format: uuid
            description: Identifier for specific event    
          required: true                               
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'                                                                  
      responses:
        200:
          description: The calendar event created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'                
    delete:
      tags:
        - 🎟️ Event
      summary: Delete a specific calendar event for a specific account
      operationId: deleteEvent
      parameters:
        - in: header
          name: x-anno-awesome
          required: true
          schema:
            type: string
            description: Identifier for specific account   
        - in: path
          name: eventId
          schema:
            type: string
            format: uuid
            description: Identifier for specific event    
          required: true                           
      responses:
        '200':
          description: Echo of the created event object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
  /event/test:
    get:
      tags:
        - 🎟️ Event
      summary: Testing if the service is operational
      operationId: testEvent
      responses:
        '200':
          description: Endpoint and version information
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  version:
                    type: string              
                    format: date
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid                
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string              
          format: date-time
        email:
          type: string
          format: email                
        password:
          type: string
          format: password
        role:
          type: string                        
        isVerified:
          type: integer
    Calendar:
      type: object
      properties:
        id:
          type: string
          format: uuid                
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string              
          format: date-time
        accountId:
          type: string
          format: uuid                
        name:
          type: string              
        color:
          type: string              
        isShared:
          type: integer
        isPublic:
          type: integer
        isActive:
          type: integer
    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid                
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string              
          format: date-time
        calendarId:
          type: string
          format: uuid                          
        startsAt:
          type: string              
          format: date
        endsAt:
          type: string              
          format: date
        summary:
          type: string
        location:
          type: string                                  
        latitude:
          type: number
        longitude:
          type: number
        url:
          type: string
          format: uri                    
        description:
          type: string                    